src/spaceone/repository/service/plugin_service.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

Revert get_version

---

src/spaceone/repository/api/v1/plugin.py
src/spaceone/repository/connector/repository_connector.py
src/spaceone/repository/manager/plugin_manager/remote_plugin_manager.py
src/spaceone/repository/service/plugin_service.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

Reverse ordered list of get_versions

---

src/spaceone/repository/service/plugin_service.py
src/spaceone/repository/service/repository_service.py
src/spaceone/repository/service/schema_service.py

archiving domain secret when domain is deleted

---

src/spaceone/repository/api/v1/plugin.py
src/spaceone/repository/api/v1/repository.py
src/spaceone/repository/api/v1/schema.py
src/spaceone/repository/info/repository_info.py

Bug fix: list minimal option

---

src/spaceone/repository/manager/repository_manager/remote_repository_manager.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

Remove debug code for token

---

README.md
pkg/pip_requirements.txt
src/setup.py
src/spaceone/repository/connector/registry_connector.py
src/spaceone/repository/error/repository.py
src/spaceone/repository/manager/plugin_manager/local_plugin_manager.py

Configuration Example
~~~
CONNECTORS:
RegistryConnector:
host: https://<account_id>.dkr.<region_name>.amazonaws.com
verify_ssl: False
api_version: 2
username: AWS
~~~
You already have to set IAM permission for get ECR token in your repository service.
Signed-off-by: “Choonho <choonhoson@megazone.com>

Support AWS ECR repository

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py

Change a aggregate lookup field's name

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py

Change aggregate lookup settings

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py

Remove aggregate lookup conf in model

---

src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py
src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py
src/spaceone/repository/service/plugin_service.py
src/spaceone/repository/service/policy_service.py
src/spaceone/repository/service/schema_service.py
test/api/test_plugin_api.py
test/api/test_policy_api.py
test/api/test_schema_api.py
test/factory/plugin_factory.py
test/factory/policy_factory.py
test/factory/schema_factory.py
test/service/test_plugin_service.py
test/service/test_policy_service.py
test/service/test_schema_service.py

Change tags field format

---

src/spaceone/repository/service/plugin_service.py
src/spaceone/repository/service/policy_service.py
src/spaceone/repository/service/schema_service.py

Change tag search spec

---

src/spaceone/repository/api/v1/policy.py
src/spaceone/repository/connector/repository_connector.py
src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py
src/spaceone/repository/manager/policy_manager/remote_policy_manager.py
src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py
test/factory/plugin_factory.py
test/factory/policy_factory.py
test/factory/schema_factory.py

add updated_at field to plugin, schema and policy resources

Bug fix: list and get policy apis

---

src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py
src/spaceone/repository/manager/policy_manager/local_policy_manager.py
src/spaceone/repository/manager/schema_manager/local_schema_manager.py

Remove domain_id filter when call get_plugin and get_schema

---

src/spaceone/repository/conf/global_conf.py
src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/repository_model.py
src/spaceone/repository/model/schema_model.py

Apply db index and unique check features

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/model/schema_model.py

Add db indexes

---

src/spaceone/repository/service/plugin_service.py

- update sorted list
Signed-off-by: “Choonho <choonhoson@megazone.com>

Fix get_version

---

src/spaceone/repository/service/plugin_service.py

Signed-off-by: “Choonho <choonhoson@megazone.com>

get_version sort logic update

---

src/spaceone/repository/service/policy_service.py

Fix a authorization bug

---

src/spaceone/repository/service/plugin_service.py
src/spaceone/repository/service/policy_service.py
src/spaceone/repository/service/schema_service.py

Fix repository api's auth config

---

src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py

Fix datetime field bugs

---

src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py

Fix a tags response bug

---

src/spaceone/repository/conf/global_conf.py

Change local cache ttl

---

src/spaceone/repository/connector/identity_connector.py
src/spaceone/repository/connector/repository_connector.py
src/spaceone/repository/connector/secret_connector.py

Support TLS communication in gRPC client.

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/service/plugin_service.py

plugin_id is name of docker image name
It was
plugin-12345678. (random number)
Now
plugin-keycloak-oidc. (docker image is spaceone/plugin-keycloak-oidc)
Signed-off-by: Choonho Son <choonhoson@megazone.com>

Change plugin_id human readable

---

deploy/helm/config/config.yaml
src/spaceone/repository/service/policy_service.py

Change handler settings

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py

Change plugin_id and policy_id's max length

---

src/spaceone/repository/service/policy_service.py

fix: fix loop issue on authorization

---

src/spaceone/repository/service/plugin_service.py
src/spaceone/repository/service/schema_service.py

fix: fix permission issue

---

src/spaceone/repository/service/policy_service.py

fix: fix argument bug

---

src/spaceone/repository/service/policy_service.py

fix: change permissions

---

src/spaceone/repository/info/plugin_info.py
src/spaceone/repository/info/policy_info.py
src/spaceone/repository/info/schema_info.py

fix: fix info bug

---

.github/PULL_REQUEST_TEMPLATE.md
src/spaceone/repository/error/policy.py
src/spaceone/repository/model/policy_model.py
src/spaceone/repository/service/policy_service.py
test/spacectl/policy-invalid-format.yml
test/spacectl/policy-ok.yml
test/spacectl/policy-too-long.yml

API parameter modified in spaceone api repo. 
Thus, related comment about document structure modified.

create policy param mofified

---

src/spaceone/repository/model/policy_model.py
src/spaceone/repository/service/policy_service.py

- [O] New feature
Added state parameter for policy

feat: add state parameter

---

src/spaceone/repository/info/policy_info.py

updated policyinfo function to support state parameter modification

fix: update policyinfo

---

src/spaceone/repository/conf/global_conf.py

remove unused config (DATABASE_CASE_INSENSITIVE_INDEX)

refactor: remove unused configuration

---

src/spaceone/repository/model/plugin_model.py
src/spaceone/repository/model/policy_model.py
test/factory/plugin_factory.py

1. Plugin 제거 시 더이상 보관하지 않도록 변경
2. Plugin과 Policy의 DELETED State 제거

refactor: change to not archiving when the plugin is deleted.
